workflows:
    react-native-android:
        name: React Native Android
        max_build_duration: 120
        instance_type: mac_mini
        environment:
            groups:
                - react-recoil-app 
            vars:
                CM_KEYSTORE_PASSWORD: Encrypted()
                CM_KEY_PASSWORD: Encrypted()
                CM_KEY_ALIAS: Encrypted()
            node: 16.14.0
        scripts:
            - yarn install
            - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$CM_BUILD_DIR/android/local.properties"
            - |
                chmod -R 777 $CM_BUILD_DIR
                echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/keystore.jks
                # build Android
                cd android
                ./gradlew assembleRelease
        artifacts:
            - android/app/build/outputs/**/*.apk
    react-native-ios:
        name: React Native iOS
        max_build_duration: 120
        instance_type: mac_mini
        environment:
            vars:
                XCODE_WORKSPACE: "ios/ReduxVsRecoil.xcworkspace"
                XCODE_SCHEME: "ReduxVsRecoil"
                BUNDLE_ID: "io.codemagic.ReduxVsRecoil"
                APP_STORE_APP_ID: 1555555551 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
            node: 16.14.0
            xcode: 12.5
            cocoapods: default
        scripts:
            - name: Install yarn dependencies
              script: |
                yarn install
            - name: Install CocoaPods dependencies
              script: |
                cd ios && pod install
#             - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
#               script: |
#                 keychain initialize
#             - name: Fetch signing files
#               script: |
#                 app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
#             - name: Use system default keychain
#               script: |
#                 keychain add-certificates
#             - name: Increment build number
#               script: |
#                 #!/bin/sh
#                 set -e
#                 set -x
#                 cd $CM_BUILD_DIR/ios
#                 # agvtool new-version -all $(($BUILD_NUMBER + 1))
#                 agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
            - name: Set up code signing settings on Xcode project
              script: |
                xcode-project use-profiles --warn-only
            - name: Build ipa for distribution
              script: |
                xcode-project build-ipa --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME" 
        artifacts:
            - build/ios/ipa/*.ipa
            - /tmp/xcodebuild_logs/*.log
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
